-- liquibase formatted sql
-- liquibase formatted sql

-- changeset DELL:1733471224912-1
--precondition-sql-check expectedResult:1 select count(*) from information_schema.tables where table_name='expenses'
CREATE TABLE "expenses" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "amount" FLOAT8, "category" VARCHAR(255), "date" date, "description" VARCHAR(255), CONSTRAINT "expenses_pkey" PRIMARY KEY ("id"));
--rollback DROP TABLE expenses

-- changeset DELL:1733471224912-2
--precondition-sql-check expectedResult:1 select count(*) from information_schema.tables where table_name='users'
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(255), "name" VARCHAR(255), "password" VARCHAR(255), CONSTRAINT "users_pkey" PRIMARY KEY ("id"));


-- changeset DELL:1733471300094-1
--preCondition-sql-check expectedResult:0 select(*) from expenses
INSERT INTO "expenses" ("id", "amount", "category", "date", "description") VALUES (2, 800.0, 'SHOPPING', '2024-11-26', 'hoodie ');
INSERT INTO "expenses" ("id", "amount", "category", "date", "description") VALUES (3, 800.0, 'SHOPPING', '2024-11-26', 'hoodie ');
INSERT INTO "expenses" ("id", "amount", "category", "date", "description") VALUES (4, 800.0, 'SHOPPING', '2024-11-26', 'hoodie ');
INSERT INTO "expenses" ("id", "amount", "category", "date", "description") VALUES (1, 1000.5, 'FOOD', '2024-11-27', 'Updated Grocery Bill');
INSERT INTO "expenses" ("id", "amount", "category", "date", "description") VALUES (5, 800.0, 'SHOPPING', '2024-11-26', 'hoodie ');

-- changeset DELL:1733471300094-2
INSERT INTO "users" ("id", "email", "name", "password") VALUES (1, 'qj', 'ih', 'c2VjdXJlUGFzc3dvcmQxMjM=');
INSERT INTO "users" ("id", "email", "name", "password") VALUES (2, '', '', 'c2VjdXJlUGFzc3dvcmQxMjM=');
INSERT INTO "users" ("id", "email", "name", "password") VALUES (3, 'khushi@gmail.com', 'khushi', 'c2VjdXJlUGFzc3dvcmQxMjM=');
INSERT INTO "users" ("id", "email", "name", "password") VALUES (4, 'vyaskhushi@gmail.com', NULL, 'S2h1c2hpQDEyMw==');
INSERT INTO "users" ("id", "email", "name", "password") VALUES (5, 'khushiv@gmail.com', NULL, 'S2h1c2hp');
INSERT INTO "users" ("id", "email", "name", "password") VALUES (6, 'boss@gmail.com', NULL, 'Ym9zczEyMzQ1');
INSERT INTO "users" ("id", "email", "name", "password") VALUES (7, 'maya@gmail.com', NULL, 'TWF5YUAxMjM=');
INSERT INTO "users" ("id", "email", "name", "password") VALUES (8, 'dikshita@gmail.com', NULL, 'RGlrc2hpdGE=');
--rollback TRUNCATE TABLE expenses

